# Generated by Django 5.1 on 2024-08-24 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'Can view'), ('can_create', 'Can create'), ('can_edit', 'Can edit'), ('can_delete', 'can delete')]},
        ),
    ]
