"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-px2(lkxi4zmem-*av0qj7xn-(ve(xu9=42+9&9fsq42=+k)w1*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
# This setting enables the X-XSS-Protection header, 
# which helps prevent Cross-Site Scripting (XSS) attacks by instructing the
# browser to stop rendering the page if an XSS attack is detected.
SECURE_BROWSER_XSS_FILTER = True
# This setting controls the X-Frame-Options header, which determines 
# whether your site can be embedded in an iframe. 
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
# Ensure that the CSRF cookie is only sent over HTTPS
CSRF_COOKIE_SECURE = True

# Ensure that the session cookie is only sent over HTTPS
SESSION_COOKIE_SECURE = True
# Content Security Policy (CSP) Settings
# The CSP header helps prevent Cross-Site Scripting (XSS) and data injection attacks.
# This policy restricts the sources from which content (scripts, styles, images, etc.) can be loaded.
CSP_DEFAULT_SRC = ("'self'",)  # Allow content only from your own domain
CSP_SCRIPT_SRC = ("'self'",)   # Allow scripts only from your own domain
CSP_STYLE_SRC = ("'self'",)    # Allow styles only from your own domain
CSP_IMG_SRC = ("'self'",)      # Allow images only from your own domain
CSP_FONT_SRC = ("'self'",)     # Allow fonts only from your own domain
# Configure Django to recognize that the connection is secure when coming through a proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Redirect all non-HTTPS requests to HTTPS.
# This setting ensures that users are always using a secure connection.
SECURE_SSL_REDIRECT = True

# HTTP Strict Transport Security (HSTS) settings
# HSTS instructs browsers to only access the site via HTTPS for a specified time.
# Setting this to 31536000 seconds (1 year) ensures that browsers will remember to use HTTPS for this duration.
SECURE_HSTS_SECONDS = 31536000

# Include all subdomains in the HSTS policy
# This setting ensures that the HSTS policy applies to all subdomains of your site.
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# Enable HSTS preloading
# This setting allows your domain to be included in the HSTS preload list maintained by browsers.
# Enabling this helps ensure that browsers always use HTTPS from the first visit.
SECURE_HSTS_PRELOAD = True

# Ensure session cookies are only transmitted over HTTPS.
# This prevents session cookies from being sent over insecure HTTP connections,
# which helps protect session data from being intercepted.
SESSION_COOKIE_SECURE = True

# Ensure CSRF cookies are only transmitted over HTTPS.
# This prevents CSRF tokens from being sent over insecure HTTP connections,
# which helps protect against Cross-Site Request Forgery attacks.
CSRF_COOKIE_SECURE = True






ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'csp',
    'relationship_app.apps.RelationshipAppConfig',
    'bookshelf.apps.BookshelfConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
'ENGINE': 'django.db.backends.mysql',
        'NAME': 'book',
        'USER': 'root',
        'PASSWORD': 'Indespicableme11#',
        'HOST': 'Localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'bookshelf.CustomUser'
